### ISSUE TITLE
hope to add Chinese support

### ISSUE THREAD

**Issue by easonboy** [grafana/grafana-image-renderer#208] opened 2021-03-01 08:21 UTC
hope to add Chinese support. The Chinese fonts of the pictures produced by the modified plug-in are currently missing. Thank you!

**Comment by marefr** [comment] 2021-03-11 09:25
Duplicate of #78

**Comment by marefr** [comment] 2021-03-11 09:27
If you're not using Docker you have to make sure to have packages installed for chinese fonts.

**Closed by marefr** 2021-03-11 09:27 UTC
Labels: type/enhancement
