### ISSUE TITLE
Remote rendering request failed

### ISSUE THREAD

**Issue by janwillemCA** [grafana/grafana-image-renderer#174] opened 2020-08-25 12:59 UTC
**What happened**:
When i want to export an PDF report with opennms i got an grafana error: msg="Remote rendering request failed" logger=rendering renderer=http error="500 Internal Server Error"

**What you expected to happen**:
Rendered images on our reports

**How to reproduce it (as minimally and precisely as possible)**:
Create an report with opennms.

**Anything else we need to know?**:
installed with docker. 

grafana:
    image: grafana/grafana:master
    ports:
     - "3030:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3030/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: v7.2.0-d64b9d71pre (e2c7ed4b82)
- Installed plugin or remote renderer service: remote renderer service
- OS Grafana Image Renderer is installed on: Docker, debian
- User OS & Browser: MacOS, Safari
- Others:

**Comment by janwillemCA** [comment] 2020-08-25 13:45
EDIT; it does work when changing ports to default 3000:3000

**Comment by IamAliBaba** [comment] 2020-11-28 19:52
port is not problem .
#bug is SSL. Like, if Grafana is under CloudFlare its not working.
works fine even if port is not 3000 under http.

hopfully will be fixed sooner.

**Comment by AgnesToulet** [comment] 2021-06-16 13:59
Seems like the initial issue was not an issue so I'm closing this.

@IamAliBaba could you please open a new issue with your set up and debug logs? Also, could it be a duplicate of https://github.com/grafana/grafana-image-renderer/issues/151? If so, could you add your input there please?

**Closed by AgnesToulet** 2021-06-16 13:59 UTC
