### ISSUE TITLE
Does not work when IPv6 is disabled

### ISSUE THREAD

**Issue by towolf** [grafana/grafana-image-renderer#48] opened 2019-10-23 15:03 UTC
Is this plugin trying to bind to `"[::]"` ?

Because we disable IPv6 in the kernel to avoid a certain class of problems, and the plugin refuses to start with this message:
`E1023 17:01:02.999153762   20891 server_chttp2.cc:38]        {"created":"@1571842862.999100646","description":"No address added out of total 1 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":305,"referenced_errors":[{"created":"@1571842862.999093903","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.cc","file_line":436,"referenced_errors":[{"created":"@1571842862.999087065","description":"Failed to initialize UV tcp handle","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.cc","file_line":277,"os_error":"address family not supported"}]}]}`

**Comment by towolf** [comment] 2019-10-23 15:11
On my local machine it looks like, yes, it is opening a tcp6 socket:
```
$ netstat -tulpen | grep 50059
tcp6       0      0 127.0.0.1:50059         :::*                    LISTEN      1000       12703687   12515/./plugin_star 
```

Is that necessary?

Inspecting the code with strings, it shows it wants to bind `127.0.0.1:50059` only.

**Comment by Bacto** [comment] 2019-10-29 09:50
Same problem on our side.
One other problem is that the plugin starts even if it can't open a socket.

```
E1029 09:43:21.302250570      58 server_chttp2.cc:38]        {"created":"@1572342201.302226173","description":"No address added out of total 1 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":305,"referenced_errors":[{"created":"@1572342201.302221999","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.cc","file_line":436,"referenced_errors":[{"created":"@1572342201.302217873","description":"Failed to initialize UV tcp handle","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.cc","file_line":277,"os_error":"address family not supported"}]}]}
1|1|tcp|127.0.0.1:50059|grpc
Renderer plugin started
```

**Comment by Bacto** [comment] 2019-10-29 09:55
Probably related to this: https://github.com/grpc/grpc-node/issues/664

Unfortunately this issue is opened for a year now.
So basically I think grafana-image-renderer can't be used without kernel IPv6 support even if it listens only on IPv4 :(

**Comment by jinleileiking** [comment] 2020-01-07 03:47
At now, docker seems the best solution....

**Comment by gajo94** [comment] 2020-01-09 16:20
Does anyone have update according to this issue. Grafana and pictures of alert worked well before updating grafana to latest version?

**Comment by jinleileiking** [comment] 2020-01-13 09:24
This bug must be fixed in Grafana 7.x.x :)

**Comment by marefr** [comment] 2020-01-19 23:01
As mentioned earlier. use docker as the workaround. Not much we can do about this until the issue is fixed in grpc node. We will add this known issue to the documentation. You can upvote/commnet in the referenced grpc-node issue.

**Comment by gajo94** [comment] 2020-01-22 10:29
One more question, what is happening with a https://snapshots-origin.raintank.io
I have configured it, but graph in alert mail is not arriving. Issue started after updating grafana to 6.5.

**Comment by marefr** [comment] 2020-01-22 12:57
@gajo94 how is snapshots and https://snapshots-origin.raintank.io related to your alert email not including graph?

**Comment by gajo94** [comment] 2020-01-22 13:34
@marefr Lets put it this way, we have option generating snaphsot to mail via phantomjs, and we have option to use imeage-renderer, I uninstalled image renderer because of this issue, but now I m not getting snapshots to alert either with a phantomjs too.

t=2020-01-22T11:39:05+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
t=2020-01-22T11:39:05+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2020-01-22T11:39:05+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2020-01-22T11:39:05+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=``

**Comment by eloo** [comment] 2020-02-06 08:24
Hi, are there any news to get the plugin working without IPv6 enabled?

Thanks

**Comment by gajo94** [comment] 2020-02-06 08:31
> Hi, are there any news to get the plugin working without IPv6 enabled?
> 
> Thanks

I managed to get it to work in a docker container in same server, thats the only way for now.

**Comment by eloo** [comment] 2020-02-06 09:31
Sadly using a separate docker container for only a plugin doesn't fit our architecture right now.
We are deploying Grafana as binary right now into a PaaS.

**Comment by Espe0n** [comment] 2020-02-27 14:55
Hi,
We are also affected by the problem. 
Are there already information’s when the error can be fixed?

**Comment by aknuds1** [comment] 2020-05-06 10:10
I wonder if this problem would go away if we would use grpc-js instead, since the issue happens within the gRPC library.

**Comment by aknuds1** [comment] 2020-05-06 12:23
I've made a PR to attempt migrating to @grpc/grpc-js, which should hopefully not have this bug: https://github.com/grafana/grafana-image-renderer/pull/135.

**Closed** 2020-05-13 11:54 UTC
Labels: type/bug
