### ISSUE TITLE
Failed to get browser version            

### ISSUE THREAD

**Issue by PragueJoker** [grafana/grafana-image-renderer#195] opened 2020-12-01 04:42 UTC
I need to help for "EROR[12-01|12:36:54] Failed to get browser version            logger=plugins.backend pluginId=grafana-image-renderer err=map[name:TimeoutError] "

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.2.1
- Installed plugin or remote renderer service:plugin
- OS Grafana Image Renderer is installed on: ”CentOS Linux release 7.8.2003 (Core)“
- User OS & Browser: mac & chrome
- Others:

**Comment by aknuds1** [comment] 2020-12-01 07:57
I think this could be caused by missing dependencies in your system, so the browser won't launch. Please read our [troubleshooting documentation](https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshoot-image-rendering). Closing this until more evidence of a bug is eventually provided.

If you shoudl be in need of support, please use our community [https://community.grafana.com](forums) or [Slack](http://slack.raintank.io).

**Closed by aknuds1** 2020-12-01 07:57 UTC

**Comment by T-Bhuiyan** [comment] 2021-05-06 00:06
Hi, I'm facing the exact same problem. All dependencies are installed, Ubuntu 16.04.7 LTS, Grafana 7.5.5
![Capture](https://user-images.githubusercontent.com/29388027/117224224-ab808080-ae0f-11eb-9087-1eacca16f56a.PNG)
