### ISSUE TITLE
Failed to start renderer plugin: Unrecognized remote plugin message

### ISSUE THREAD

**Issue by mieseprem** [grafana/grafana-image-renderer#150] opened 2020-06-03 13:08 UTC
**What happened**:
I did my first steps with Grafana 7.0.1. I knew the breaking change that PhantomJS was removed and grafana-image-renderer is to be used.
Therefore I switched already to grafana-image-renderer on my Grafana 6.7.3 installation.

I install Plugins via environment variables I provide at image build time:
GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
GF_INSTALL_PLUGINS=grafana-image-renderer,grafana-piechart-panel,jdbranham-diagram-panel,snuids-trafficlights-panel

Now I simply replaced Grafana version from 6.7.3 to 7.0.1 in Dockerfile.

This is the log of Grafana container startup:

> installing grafana-image-renderer @ 2.0.0
> from: https://grafana.com/api/plugins/grafana-image-renderer/versions/2.0.0/download 
> into: /var/lib/grafana/plugins
> 
> ✔ Installed grafana-image-renderer successfully 
> 
> Restart grafana after installing plugins . <service grafana-server restart>
> 
> installing grafana-piechart-panel @ 1.5.0
> from: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.5.0/download 
> into: /var/lib/grafana/plugins
> 
> ✔ Installed grafana-piechart-panel successfully 
> 
> Restart grafana after installing plugins . <service grafana-server restart>
> 
> installing jdbranham-diagram-panel @ 1.6.2
> from: https://grafana.com/api/plugins/jdbranham-diagram-panel/versions/1.6.2/download 
> into: /var/lib/grafana/plugins
> 
> ✔ Installed jdbranham-diagram-panel successfully 
> 
> Restart grafana after installing plugins . <service grafana-server restart>
> 
> installing snuids-trafficlights-panel @ 1.4.5
> from: https://grafana.com/api/plugins/snuids-trafficlights-panel/versions/1.4.5/download 
> into: /var/lib/grafana/plugins
> 
> ✔ Installed snuids-trafficlights-panel successfully 
> 
> Restart grafana after installing plugins . <service grafana-server restart>
> 
> t=2020-06-03T11:08:59+0000 lvl=info msg="Starting Grafana" logger=server version=7.0.1 commit=ef5b586d7d branch=HEAD compiled=2020-05-26T08:05:56+0000
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/ini/grafana.ini
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
> t=2020-06-03T11:08:59+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
> t=2020-06-03T11:08:59+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
> t=2020-06-03T11:08:59+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
> t=2020-06-03T11:08:59+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
> t=2020-06-03T11:08:59+0000 lvl=info msg="App mode production" logger=settings
> t=2020-06-03T11:08:59+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
> t=2020-06-03T11:08:59+0000 lvl=info msg="Starting DB migration" logger=migrator
> t=2020-06-03T11:08:59+0000 lvl=info msg="Executing migration" logger=migrator id="Add index user.login/user.email"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for dashboard_title"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Executing migration" logger=migrator id="Add uid column"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Executing migration" logger=migrator id="Update uid value"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Executing migration" logger=migrator id="Add unique index datasource_org_id_uid"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Starting plugin search" logger=plugins
> t=2020-06-03T11:08:59+0000 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Registering plugin" logger=plugins name="Grafana Image Renderer"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
> t=2020-06-03T11:08:59+0000 lvl=info msg="Registering plugin" logger=plugins name=Diagram
> t=2020-06-03T11:08:59+0000 lvl=info msg="Registering plugin" logger=plugins name="Traffic Lights"
> t=2020-06-03T11:08:59+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
> t=2020-06-03T11:08:59+0000 lvl=eror msg="Stopped RenderingService" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
> t=2020-06-03T11:08:59+0000 lvl=info msg="Stopped Stream Manager"
> t=2020-06-03T11:08:59+0000 lvl=warn msg="plugin failed to exit gracefully" logger=plugins.backend pluginId=grafana-image-renderer
> t=2020-06-03T11:09:00+0000 lvl=eror msg="A service failed" logger=server err="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
> t=2020-06-03T11:09:00+0000 lvl=eror msg="Server shutdown" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."

**What you expected to happen**:
As I googled the error message and found merged pull request #135 I expected the image-renderer plugin to start successfully als installed plugin (and not as dedicated service)

**How to reproduce it (as minimally and precisely as possible)**:
Build Grafana Image based on "FROM grafana/grafana:7.0.1" and provide at startup the environment variables mentioned above

**Anything else we need to know?**:

Same setup but with Grafana version 6.7.3 works fine.

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.0.1
- Installed plugin or remote renderer service: installed as plugin
- OS Grafana Image Renderer is installed on: 
> /usr/share/grafana $ cat /etc/os-release 
> NAME="Alpine Linux"
> ID=alpine
> VERSION_ID=3.10.4
> PRETTY_NAME="Alpine Linux v3.10"
> HOME_URL="https://alpinelinux.org/"
> BUG_REPORT_URL="https://bugs.alpinelinux.org/"
> /usr/share/grafana $ id
> uid=1002080000 gid=0(root) groups=2075,1002080000
- User OS & Browser: -
- Others: -

**Comment by aknuds1** [comment] 2020-06-03 13:15
Closing as duplicate of #148 - please let us know if your case actually differs.

**Closed by aknuds1** 2020-06-03 13:15 UTC
