### ISSUE TITLE
Remote Renderer Times Out if Grafana Panel has not been SAVED

### ISSUE THREAD

**Issue by kaijk** [grafana/grafana-image-renderer#157] opened 2020-06-16 21:48 UTC
**What happened**:
Remote Renderer times out when rendering "unsaved" Panel
**What you expected to happen**:
Rendering to complete successfully or message raised about needing to save the Panel first.
**How to reproduce it (as minimally and precisely as possible)**:

1. Create a NEW Panel (without SAVING or APPLYing)
2. Navigate to Share > Direct link rendered image
3. Click the link to create the Rendered Image
After 60 seconds the rendering will time-out
1. Select APPLY and repeat rendering process
It will time-out again
1. SAVE the Panel to a Dashboard and repeat the rendering process
The Render will succeed

**Anything else we need to know?**:
Consider raising a nag message before the results browser tab is opened to first save the Panel if the Render link is clicked on an unsaved Panel 

**Environment**:
- Grafana Image Renderer version:
2.0.0
- Grafana version:
7.0.3
- Installed plugin or remote renderer service:
Remote Renderer service
- OS Grafana Image Renderer is installed on:
Grafana: Docker on Rasbpian Buster Lite on RasPi 3+B
Renderer: Docker on Win10 Professional
- User OS & Browser:
Win10, Firefox
- Other:
Relevant log messages:
grafana          | t=2020-06-16T21:35:14+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Failed to send request to remote rendering service. Get \"http://192.168.[YY].[XXX]:8081/render?deviceScaleFactor=1.000000&domain=192.168.[YY].[ZZZ]&encoding=&height=500&renderKey=VorR7zPu7RxRr5IIIFwikL0lb34hKYkl&timeout=60&timezone=America%2FLos_Angeles&url=http%3A%2F%2F192.168.[YY].[ZZZ]%3A3000%2Fd-solo%2FnXibuqmgz%2Fswitch%3ForgId%3D1%26from%3D1592321650041%26to%3D1592343250041%26panelId%3D6%26width%3D1000%26height%3D500%26tz%3DAmerica%252FLos_Angeles%26render%3D1&width=1000\": context deadline exceeded"
grafana          | t=2020-06-16T21:35:14+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/nXibuqmgz/switch status=500 remote_addr=192.168.[YY].[XXX] time_ms=62116 size=1723 referer="http://192.168.[YY].[ZZZ]:3000/d/nXibuqmgz/switch?editPanel=6&orgId=1&from=now-6h&to=now"

**Comment by aknuds1** [comment] 2020-06-17 06:39
I can reproduce the issue. Thanks for reporting it!

**Comment by aknuds1** [comment] 2020-06-17 06:43
It's a bug in Grafana, not the renderer. I'll make an issue in the Grafana repo.

**Comment by aknuds1** [comment] 2020-06-17 06:56
I made a bug for handling such invalid panels in #158. Grafana [bug](https://github.com/grafana/grafana/issues/25648).

**Comment by aknuds1** [comment] 2020-06-17 06:57
Closing in favour of #158, since it's more specific.

**Closed by aknuds1** 2020-06-17 06:57 UTC
Labels: type/bug
