### ISSUE TITLE
Trouble with armv7l (docker on Raspberry Pi 3B+)

### ISSUE THREAD

**Issue by jonathandreyer** [grafana/grafana-image-renderer#14] opened 2019-03-21 17:32 UTC
Hello,
I have run on a docker container (target x86_64) and it is Ok. On target armv7l (Raspberry Pi (3B+), it is not work.

It is crash on line:
https://github.com/grafana/grafana-image-renderer/blob/3989c1dacd2121ca2a1b3e306bef095a0300db62/Dockerfile#L13

**Comment by jonathandreyer** [comment] 2019-03-21 18:21
After some tests, there is no more crash when dumb-init is removed.

**Comment by marefr** [comment] 2019-11-14 01:18
Duplicate of #7

**Closed by marefr** 2019-11-14 01:18 UTC
