### ISSUE TITLE
ARM64 for Linux Plugin support

### ISSUE THREAD

**Issue by ksquaredkey** [grafana/grafana-image-renderer#512] opened 2024-04-01 20:18 UTC
I am confused as I found 3 closed issues with PRs on this topic (#65, #346, and #424) yet the README.md, the release artifacts, and the attempt to do a "grafana-cli plugins install grafana-image-renderer" all indicate ARM64 is still not supported.  In particular, it appears that #424 was prematurely closed.

**What would you like to be added**:
Released plugins supported on arm64 linux (bonus for arm64 darwin)

**Why is this needed**:
The cloud world has been moving to ARM64 for quite some time.

**Comment by AgnesToulet** [comment] 2024-04-02 07:52
Hello! The grafana-image-renderer can be run in two ways: as a remote server and as a plugin. Since this PR https://github.com/grafana/grafana-image-renderer/pull/468, we are now releasing a Docker image for ARM64 that will allow you to run it as a remote server. We do not support this architecture for the plugin, though. This is why the following issue is still open: https://github.com/grafana/grafana-image-renderer/issues/7

Closing this as a duplicate of https://github.com/grafana/grafana-image-renderer/issues/7

**Closed by AgnesToulet** 2024-04-02 07:52 UTC

**Comment by ksquaredkey** [comment] 2024-04-03 17:25
Ah, got it - thank you!  The Grafana Enterprise documentation keeps pointing towards the plugin solution that I glossed over the documentation on the remote server form.  In 20/20 hindsight, the remote server solution is actually what I prefer as I already expressed concerns on the memory requirements affecting our other users in our shared Grafana instances.
