### ISSUE TITLE
Panel rendering fails with TimeoutError

### ISSUE THREAD

**Issue by pcantea** [grafana/grafana-image-renderer#261] opened 2021-07-27 17:36 UTC
**What happened**: Rendering panel fails with TimeoutError

**What you expected to happen**: Panel renders

**Environment**:
- Grafana Image Renderer version: v3.0.1
- Grafana version: 7.4.5
- Installed plugin or remote renderer service: remote renderer
- OS Grafana Image Renderer is installed on: Docker
- User OS & Browser: 
- Others:

logs:
```
grafana-image-renderer-9dd79c7f6-2fn2v grafana-image-renderer {"config":{"chromeBin":"/usr/bin/chromium-browser","args":["--no-sandbox"],"ignoresHttpsErrors":false,"acceptLanguage":null,"width":1000,"height":500,"deviceScaleFactor":1,"maxWidth":3080,"maxHeight":3000,"maxDeviceScaleFactor":3,"mode":"default","clustering":{"mode":"browser","maxConcurrency":5},"verboseLogging":true,"dumpio":true},"level":"debug","message":"Browser initialized"}
grafana-image-renderer-9dd79c7f6-2fn2v grafana-image-renderer {"url":"http://grafana.monitoring:80/dashboard-solo/db/kubernetes-cluster-monitoring-via-prometheus?panelId=32&from=now-1M%2FM&to=now-1M%2FM&width=1150&height=250&render=1","level":"debug","message":"Connection closed"}
grafana-image-renderer-9dd79c7f6-2fn2v grafana-image-renderer {"message":"10.7.43.18 - - [27/Jul/2021:17:15:59 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=grafana.monitoring&encoding=&height=250&renderKey=y4Digl1SAIgBg7b3889akDxmbmp4ulPM&timeout=60&timezone=&url=http%3A%2F%2Fgrafana.monitoring%3A80%2Fdashboard-solo%2Fdb%2Fkubernetes-cluster-monitoring-via-prometheus%3FpanelId%3D32%26from%3Dnow-1M%252FM%26to%3Dnow-1M%252FM%26width%3D1150%26height%3D250%26render%3D1&width=1150 HTTP/1.1\" - - \"-\" \"Grafana/7.4.5\"\n","level":"debug"}
grafana-image-renderer-9dd79c7f6-2fn2v grafana-image-renderer {"url":"/render?deviceScaleFactor=1.000000&domain=grafana.monitoring&encoding=&height=250&renderKey=y4Digl1SAIgBg7b3889akDxmbmp4ulPM&timeout=60&timezone=&url=http%3A%2F%2Fgrafana.monitoring%3A80%2Fdashboard-solo%2Fdb%2Fkubernetes-cluster-monitoring-via-prometheus%3FpanelId%3D32%26from%3Dnow-1M%252FM%26to%3Dnow-1M%252FM%26width%3D1150%26height%3D250%26render%3D1&width=1150","stack":"TimeoutError: Navigation timeout of 60000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:191:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","level":"error","message":"Request failed"}

```

**Comment by nirav-radia-sp** [comment] 2021-08-11 18:24
Bump, we're also seeing this issue but with v2.1.1. Haven't upgraded to v3.0.1 yet

```
{
    "url": "/render?deviceScaleFactor=1.000000&domain=<REDACTED_URL>",
    "stack": "TimeoutError: Navigation timeout of 60000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "level": "error",
    "message": "Request failed"
}
```

Any workaround or fix available?

**Comment by AgnesToulet** [comment] 2021-09-02 15:57
That may be something in your set up preventing the image renderer to access your Grafana instance. We would need more logs to help you debugging this issue. Do you see in the Grafana logs that a request to this endpoint `http://grafana.monitoring:80/dashboard-solo/db/kubernetes-cluster-monitoring-via-prometheus?panelId=32&from=now-1M%2FM&to=now-1M%2FM&width=1150&height=250&render=1` is made?

Also is this something that happens all the time or only from time to time? Is this reproducible with a simple panel with dummy data?

**Comment by AgnesToulet** [comment] 2023-04-14 12:21
Closing this as waiting for more info since Sept 2021.

**Closed by AgnesToulet** 2023-04-14 12:21 UTC
Labels: needs more info
