### ISSUE TITLE
Image renderer is not working with the following exception

### ISSUE THREAD

**Issue by rnachire** [grafana/grafana-image-renderer#155] opened 2020-06-12 12:38 UTC
**What happened**: Image rendering is failing with pdf-exporter

**What you expected to happen**: It has to fetch the images from each panel and show as part of pdf exporter or atleast it should show the rendered image with API

**How to reproduce it (as minimally and precisely as possible)**: Please use use the below mentioned versions to reproduce the issue

**Environment**: Kubernetes 1.17
- Grafans pdf-exporter version: izakmarais/grafana-reporter:2.3.1
- Grafana Image Renderer version: grafana-image-renderer @ 2.0.0
- Grafana version: 7.0.3 and 7.0.0
- Installed plugin or remote renderer service: installed plugin (grafana-cli plugins install grafana-image-renderer in docker image to use in k8s)
- OS Grafana Image Renderer is installed on:Centos
- User OS & Browser: Ubuntu 16.0.4 and Google Chrome 
- Others: Following are the logs 

Few rendering issues seen while integrating the pdf -exporter as it has image-rendering plugin as a prerequisite.

Server logs:

> {{t=2020-06-15T05:01:23+0000 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:3000/grafana/d-solo/FMXkAdlWk1/_?from=now-1h&height=500&panelId=29&theme=light&to=now&width=1000&render=1" error="Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: }}https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md%5Cn%22{{ }}
> {{t=2020-06-15T05:01:23+0000 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:3000/grafana/d-solo/FMXkAdlWk1/_?from=now-1h&height=500&panelId=59&theme=light&to=now&width=1000&render=1" error="Error: Failed to launch chrome!\n\n\nTROUBLESHOOTING: }}https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md%5Cn%22{{ }}

Exporter logs:

> error rendering PNGs in parralel for dash {Title:Cluster Health Description:https://grafana.com/dashboards/3119 - Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, control plane (as deployed by kops) statistics. Uses cAdvisor metrics only.Tweaked from original https://grafana.com/dashboards/315 to add templating for:- adaptable \$interval (instead of hardcoded 1m)- selectable \$datasource (very useful to have a single dashboard tackling several prometheis ) VariableValues: Rows:[] Panels:[{Id:56 Type:table Title:Resource Allocations \& Usage GridPos:{H:11 W:24 X:0 Y:1}} {Id:46 Type:graph Title:Cluster Memory Usage GridPos:{H:5 W:24 X:0 Y:14}} {Id:47 Type:graph Title:Cluster CPU Usage GridPos:{H:5 W:24 X:0 Y:19}} {Id:32 Type:graph Title:Top5 Node CPU Usage \% GridPos:{H:5 W:24 X:0 Y:24}} {Id:51 Type:graph Title:Top5 Node Memory Usage GridPos:{H:5 W:24 X:0 Y:29}} {Id:52 Type:graph Title:Top5 Node Disk Usage GridPos:{H:5 W:24 X:0 Y:34}} {Id:17 Type:graph Title:Pods CPU usage (\$interval avg) GridPos:{H:7 W:24 X:0 Y:41}}]}: error getting panel {Id:32 Type:graph Title:Top5 Node CPU Usage % GridPos:{H:5 W:24 X:0 Y:24: Error obtaining render: 500 Internal Server Error}}

  

>     - name: grafana-reporter
>         image: izakmarais/grafana-reporter:2.3.1
>         args:
>         - --proto=https://
>         - --ip=172.16.22.84:30101
>         - --ssl-check=false
>         ports:
>         - containerPort: 8686
>           protocol: TCP
> 

Please help us solvign the above issue and let us know if any other logs required to isolate the issue

**Comment by aknuds1** [comment] 2020-06-16 05:50
Please rewrite the issue description using the standard bug template.

**Comment by rnachire** [comment] 2020-06-16 06:22
Updated the issue with standard template and please lookinto and help us with resolution

**Comment by aknuds1** [comment] 2020-06-16 06:26
Please describe in enough detail how to reproduce the issue in the "How to reproduce it (as minimally and precisely as possible)" section. Right now, I have no idea how to reproducew.

**Comment by aknuds1** [comment] 2020-06-16 06:28
If you're having trouble with IzakMarais/reporter, I suggest you report the issue there first and eventually return to us if there's actually a bug in grafana/image-renderer. We can't provide support for 3rd party integrations.

**Comment by rnachire** [comment] 2020-06-16 06:32
Hi, 

there is no issue with the pdf-exporter because i could see the the image not available in pdf.. I have tried the render image  with api endpoint from grafana server logs..

Following docker-compose can be used to reproduce the issue

version: '3.2'

services:

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    expose:
      - 3000
    ports:
      - "3000:3000"

  reporter:
    image: izakmarais/grafana-reporter:${gr_version:-latest}
    command: "-ip grafana:3000"
    ports:
      - "8080:8686"

**Comment by aknuds1** [comment] 2020-06-16 06:32
Ah, from reading your logs I think you are missing a dependency, libX11.so.6.

**Comment by aknuds1** [comment] 2020-06-16 06:33
Please read the troubleshooting [doc](https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin-and-remote-rendering-service).

**Comment by rnachire** [comment] 2020-06-16 06:33
Does it come automatically with image renderer plugin or we need to add the dependencies explicitly ?

**Comment by aknuds1** [comment] 2020-06-16 06:34
Closing the issue for now, since I think it should come down to missing dependencies. Please get back to us if after following the troubleshooting instructions, for installing dependencies, you are still having problems.

**Closed by aknuds1** 2020-06-16 06:34 UTC
