### ISSUE TITLE
Install Grafana Image Renderer plugin for grafana v7.0.x

### ISSUE THREAD

**Issue by Loernl** [grafana/grafana-image-renderer#154] opened 2020-06-10 09:59 UTC
When I downloaded the Grafana Image Renderer plug-in zip package and unzipped it in my Grafana plug-in installation directory, I restarted Grafana and found the following error：

```
Stopped RenderingService [31mlogger[0m=server [31mreason[0m="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
```

**Comment by NightDragon1** [comment] 2020-06-13 18:50
Same here!

**What happened**:
I Updated Grafana-docker container to the latest version (Grafana 7.0.3 / docker-hub digest f22e7f865da0) and Installed the Render Plugin with "grafana-cli plugins install grafana-image-renderer"
--> Grafana doesn't start anymore (Container running, access via exec blocked --> Recovery by deleting the plugin from the plugin folder and restarting the container)

**What you expected to happen**:
--> Rendering available to share charts as png as usually.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install latest Docker Image, create some charts
2. Install the Plugin and restart Grafana as told by the plugin installation
3. try accessing the GUI.

**Anything else we need to know?**:
Results from Console:
```
EROR[06-13|18:44:35] Stopped RenderingService                 logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
WARN[06-13|18:44:35] plugin failed to exit gracefully         logger=plugins.backend pluginId=grafana-image-renderer
INFO[06-13|18:44:35] Stopped Stream Manager 
INFO[06-13|18:44:35] HTTP Server Listen                       logger=http.server address=[::]:3000 protocol=http subUrl= socket=
EROR[06-13|18:44:35] A service failed                         logger=server err="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
EROR[06-13|18:44:35] Server shutdown                          logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
```


**Environment**:
- Grafana Image Renderer version: 2.0.0 / 2020-05-16
- Grafana version: 7.0.3
- Installed plugin or remote renderer service: Plugin
- OS Grafana Image Renderer is installed on: installed via grafana-cli directly on the 7.0.3 docker image of grafana, by executing: "grafana-cli plugins install grafana-image-renderer"
- User OS & Browser: Windows 10, Firefox 77.0.1 (64-Bit)
- Others: non

**Comment by fragpit** [comment] 2020-06-15 16:48
https://grafana.com/docs/grafana/latest/installation/docker/#build-with-grafana-image-renderer-plugin-pre-installed

**Comment by aknuds1** [comment] 2020-06-16 05:55
@NightDragon1 That looks like #148.

**Comment by WolverMinion** [comment] 2020-07-17 07:14
suggestion: install in your image chromium package
i use `grafana/grafana:7.1.0` and `https://github.com/grafana/grafana-image-renderer/releases/download/v2.0.0/plugin-linux-x64-glibc.zip`

```Dockerfile
FROM grafana/grafana:7.1.0
...
....
RUN apk update \
    && apk --no-cache upgrade \
    && apk --no-cache add curl unzip chromium
....
....
RUN apk del curl unzip tar \
    && rm -rf /var/cache/apk/*
....
```

it runs with me

**Comment by marefr** [comment] 2020-07-17 12:09
@WolverMinion thanks, but there's already instructions in documentation regarding this, see https://grafana.com/docs/grafana/latest/administration/image_rendering/#run-in-custom-grafana-docker-image

**Comment by tholu** [comment] 2020-10-07 08:46
@marefr Is it enough to set `GF_RENDERING_SERVER_URL` and `GF_RENDERING_CALLBACK_URL` in the Grafana docker image for Grafana to recognize it should use the external renderer service?

I still get this:

`grafana_1                 | t=2020-10-07T08:37:01+0000 lvl=warn msg="Could not render image, no image renderer found/installed. For image rendering support please install the grafana-image-renderer plugin. Read more at https://grafana.com/docs/grafana/latest/administration/image_rendering/" logger=rendering`

**Comment by ploksa** [comment] 2020-10-08 18:34
good evening, may I ask if there is anything new to this issue? I run into the same problems with grafana 6.4.2 on OL7.7. I unzipped the plugin to plugin directory, did a restart of grafana and it failed to start with following error in grafana.log "t=2020-10-08T18:07:23+0200 lvl=eror msg="Stopped RenderingService" logger=server reason="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or 
simply\nneeds to be recompiled to support the latest protocol.""
Should I open a separate bug report?
thank you

**Comment by aknuds1** [comment] 2020-10-09 07:56
@ploksa It sounds as if the Chromium browser fails to start due to missing dependencies on your system.

**Comment by ploksa** [comment] 2020-10-09 12:11
according to install guide it should be possible to use the plugin from version 5. 
https://grafana.com/grafana/plugins/grafana-image-renderer/installation?version=2.0.0

I see that some packages mentioned in troubleshooting guide form centos are missing, but when i do a check with ldd on chrome binary in plugin and it looks ok.

ldd chrome-linux/chrome
        linux-vdso.so.1 =>  (0x00007fffdf33b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007febf13ba000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007febf119e000)
        librt.so.1 => /lib64/librt.so.1 (0x00007febf0f96000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007febf0c58000)
        libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007febf0a56000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007febf082e000)
        libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007febf062b000)
        libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007febf0420000)
        libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007febf021d000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007febf000b000)
        libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007febefe05000)
        libXi.so.6 => /lib64/libXi.so.6 (0x00007febefbf5000)
        libXrender.so.1 => /lib64/libXrender.so.1 (0x00007febef9ea000)
        libXtst.so.6 => /lib64/libXtst.so.6 (0x00007febef7e4000)
        libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007febef593000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007febef27d000)
        libnss3.so => /lib64/libnss3.so (0x00007febeef4e000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007febeed1e000)
        libsmime3.so => /lib64/libsmime3.so (0x00007febeeaf6000)
        libnspr4.so => /lib64/libnspr4.so (0x00007febee8b8000)
        libcups.so.2 => /lib64/libcups.so.2 (0x00007febee64f000)
        libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007febee3ff000)
        libXss.so.1 => /lib64/libXss.so.1 (0x00007febee1fb000)
        libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007febede5c000)
        libexpat.so.1 => /lib64/libexpat.so.1 (0x00007febedc32000)
        libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007febeda27000)
        libasound.so.2 => /lib64/libasound.so.2 (0x00007febed727000)
        libm.so.6 => /lib64/libm.so.6 (0x00007febed425000)
        libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007febed1ff000)
        libatk-bridge-2.0.so.0 => /lib64/libatk-bridge-2.0.so.0 (0x00007febecfd0000)
        libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007febecdc2000)
        libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007febecb7c000)
        libcairo.so.2 => /lib64/libcairo.so.2 (0x00007febec845000)
        libatspi.so.0 => /lib64/libatspi.so.0 (0x00007febec614000)
        libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007febebd0c000)
        libgdk-3.so.0 => /lib64/libgdk-3.so.0 (0x00007febeba22000)
        libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007febeb7fa000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007febeb5e4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007febeb216000)
        /lib64/ld-linux-x86-64.so.2 (0x00007febfb601000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007febeb012000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007febeadb0000)
        libffi.so.6 => /lib64/libffi.so.6 (0x00007febeaba8000)
        libplc4.so => /lib64/libplc4.so (0x00007febea9a3000)
        libplds4.so => /lib64/libplds4.so (0x00007febea79f000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007febea552000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007febea269000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007febea036000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007febe9e32000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007febe9bc0000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007febe975d000)
        libavahi-common.so.3 => /lib64/libavahi-common.so.3 (0x00007febe9550000)
        libavahi-client.so.3 => /lib64/libavahi-client.so.3 (0x00007febe933f000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007febe9108000)
        libz.so.1 => /lib64/libz.so.1 (0x00007febe8ef2000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007febe8cc1000)
        libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007febe8abd000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007febe8896000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007febe867d000)
        libmount.so.1 => /lib64/libmount.so.1 (0x00007febe843a000)
        libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007febe8224000)
        libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007febe7fe2000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007febe7d23000)
        libthai.so.0 => /lib64/libthai.so.0 (0x00007febe7b17000)
        libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007febe78fb000)
        libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007febe7652000)
        libEGL.so.1 => /lib64/libEGL.so.1 (0x00007febe743e000)
        libpng15.so.15 => /lib64/libpng15.so.15 (0x00007febe7213000)
        libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007febe700f000)
        libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007febe6e01000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007febe6b75000)
        libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007febe696c000)
        libwayland-client.so.0 => /lib64/libwayland-client.so.0 (0x00007febe675d000)
        libepoxy.so.0 => /lib64/libepoxy.so.0 (0x00007febe6431000)
        libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007febe622e000)
        libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007febe5fee000)
        libwayland-cursor.so.0 => /lib64/libwayland-cursor.so.0 (0x00007febe5de6000)
        libwayland-egl.so.1 => /lib64/libwayland-egl.so.1 (0x00007febe5be4000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007febe59d4000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007febe57d0000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007febe55cd000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007febe53c8000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007febe51a2000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007febe4f8d000)
        libgcrypt.so.11 => /lib64/libgcrypt.so.11 (0x00007febe4d0c000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007febe4b07000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00007febe48b6000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007febe4676000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007febe4471000)
        libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007febe41d4000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007febe3fc4000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007febe3d0e000)
        libGLX.so.0 => /lib64/libGLX.so.0 (0x00007febe3adc000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007febe38d7000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007febe36bf000)
        libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007febe3491000)

**Comment by aknuds1** [comment] 2020-10-10 15:47
It could be that the documentation is out of date, I'm not sure. I'm not familiar enough to say if the plugin protocol currently in use is incompatible with version 5, I think @marefr would know.

**Comment by AgnesToulet** [comment] 2021-06-16 13:24
Is this still an issue? If yes, please enable debug logging in Grafana and share the detailed logs as the message `Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol` can hide a lot of different issues.

To enable debug logging in Grafana, set the following in your .ini file (see [configuration documentation](https://grafana.com/docs/grafana/latest/administration/configuration/)):
```
[log]
level = debug
```

**Comment by tholu** [comment] 2021-06-16 13:34
@AgnesToulet I'll try again with the latest version, is there a working example of a `docker-compose.yml` file anywhere?

**Comment by AgnesToulet** [comment] 2021-06-16 16:47
Here it is: https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#docker-compose-example

**Comment by AgnesToulet** [comment] 2021-09-08 10:19
Closing this issue as it may have been fixed in the latest versions. Please open it again with more information if it's still an issue.

**Closed by AgnesToulet** 2021-09-08 10:19 UTC
Labels: needs more info
