### ISSUE TITLE
the server responded with a status of 503

### ISSUE THREAD

**Issue by ortiga88** [grafana/grafana-image-renderer#175] opened 2020-08-26 12:09 UTC
the image does not render me error:
```

{"collectDefaultMetrics":true,"requestDurationBuckets":"1,5,7,9,11,13,15,20,30","level":"info","message":"Metrics enabled"}
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
{"msg":"Failed to load resource: the server responded with a status of 503 (Service Unavailable)","url":"http://grafana:3000/api/datasources/proxy/1/api/v1/query_range?query=rabbitmq_node_mem_used&start=1598442960&end=1598443260&step=60","level":"error","message":"Browser console error"}
{"url":"/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=2TikCioiyhwvWp7ufyKub5jmvqEqZAem&timeout=5&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2FF8nOJlZGk%2Fservidores-ags%3ForgId%3D1%26panelId%3D7%26render%3D1&width=1000","stack":"Error: Request aborted\n    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1025:15)\n    at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1067:9)\n    at processImmediate (internal/timers.js:456:21)","level":"error","message":"Request failed"}
TypeError: Cannot read property 'statusCode' of undefined
    at /usr/src/app/build/service/http-server.js:92:46
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:127:14)
    at /usr/src/app/build/service/http-server.js:51:21
    at /usr/src/app/node_modules/express/lib/response.js:434:22
    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1027:5)
```

```
{"url":"/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=C5vOzq0sSHOyAaVUcIWW7eS7eRBxNkQC&timeout=5&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2FjTx7Zmzik%2Falertas%3ForgId%3D1%26panelId%3D7%26render%3D1&width=1000","stack":"Error: Request aborted\n    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1025:15)\n    at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1067:9)\n    at processImmediate (internal/timers.js:456:21)","level":"error","message":"Request failed"}
TypeError: Cannot read property 'statusCode' of undefined
    at /usr/src/app/build/service/http-server.js:92:46
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:127:14)
    at /usr/src/app/build/service/http-server.js:51:21
    at /usr/src/app/node_modules/express/lib/response.js:434:22
    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1027:5)

```

always the same error in some panels only appears to me

**Comment by AgnesToulet** [comment] 2021-06-16 14:02
Duplicate of https://github.com/grafana/grafana-image-renderer/issues/202

**Closed by AgnesToulet** 2021-06-16 14:02 UTC
