### ISSUE TITLE
Rendering panels with transparent background

### ISSUE THREAD

**Issue by Pepsi2006** [grafana/grafana-image-renderer#252] opened 2021-06-13 15:24 UTC
It seems that the plugin ignores the use of transparent backgrounds.
Is this a known problem, or am I doing something wrong?

-
Fredrik

**Comment by AgnesToulet** [comment] 2021-06-16 14:12
Duplicate of https://github.com/grafana/grafana-image-renderer/issues/184

**Closed by AgnesToulet** 2021-06-16 14:12 UTC
