### ISSUE TITLE
How to support https for grafana?

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana-image-renderer#50] opened 2019-11-02 09:55 UTC
grafana use https, renderer use http.

monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:47:28 http: TLS handshake error from 10.255.0.2:59292: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:47:28 http: TLS handshake error from 10.255.0.2:59293: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | t=2019-11-02T09:47:28+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:47:28 http: TLS handshake error from 10.255.0.2:59295: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:47:28 http: TLS handshake error from 10.255.0.2:59296: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:47:28 http: TLS handshake error from 10.255.0.2:59297: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:47:28 http: TLS handshake error from 10.255.0.2:59299: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:47:28 http: TLS handshake error from 10.255.0.2:59298: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | t=2019-11-02T09:47:46+0000 lvl=info msg="Successful Login" logger=http.server User=sandbox@localhost
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | 2019/11/02 09:49:01 http: TLS handshake error from 172.12.0.3:54474: remote error: tls: unknown certificate
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | t=2019-11-02T09:49:01+0000 lvl=eror msg="Remote rendering request failed" logger=rendering error="500 Internal Server Error"
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | t=2019-11-02T09:49:01+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=sandbox error="Remote rendering request failed. 500: 500 Internal Server Error"
monitor_grafana-service.1.l9og2p9i456e@ubuntu1 | t=2019-11-02T09:49:01+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=sandbox method=GET path=/render/d-solo/e5Ef8jkmz/system status=500 remote_addr=10.255.0.2 time_ms=1990 size=1722 referer="https://10.103.238.31:3000/d/e5Ef8jkmz/system?orgId=1"

Did you fix it?

**Comment by marefr** [comment] 2019-11-14 01:15
Duplicate of #33

**Closed by marefr** 2019-11-14 01:15 UTC
