### ISSUE TITLE
Docker Compose example is not working or incomplete

### ISSUE THREAD

**Issue by oholimoli** [grafana/grafana-image-renderer#207] opened 2021-02-09 12:03 UTC
**What happened**:

The example is not working:
https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#docker-compose-example

The image renderer is not installed:
![image-renderer](https://user-images.githubusercontent.com/47213738/107362705-66cb9e80-6ad9-11eb-82bc-6057c58efcf9.PNG)

**What you expected to happen**:
Open a dashboard and share a rendered image

**How to reproduce it (as minimally and precisely as possible)**:

Try this example
```
version: '2'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
```

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.4.0
- Installed plugin or remote renderer service: Remote renderer service
- OS Grafana Image Renderer is installed on: Docker

**Comment by crklonghorn** [comment] 2021-03-06 16:01
Seeing this same issue with similar versions.  I believe since you're pulling latest on the image renderer that you're actually mirroring my setup.

Environment:
Grafana Image Renderer version: 2.0.1
Grafana version: Grafana v7.4.3 (010f20c1c8)
Installed plugin or remote renderer service: Remote renderer service
OS Grafana Image Renderer is installed on: Docker

using the same config.json as the project: https://github.com/grafana/grafana-image-renderer/blob/master/devenv/docker/custom-config/config.json

When I use the image renderer 2.0.0 version I have no problems, but when I upgrade to 2.0.1 with the same configurations I get 500s in the grafana logs and timeouts on the image-renderer.

t=2021-03-06T15:42:13+0000 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/ttLM9YVGz/testing-dashboard?orgId=1&theme=light&panelId=2&fullscreen&width=830&height=323&tz=America%2FChicago"
t=2021-03-06T15:42:13+0000 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="https://redacted.domain/render?deviceScaleFactor=1.000000&domain=redacted.callback.domain&encoding=&height=323&renderKey=redeacted&timeout=60&timezone=America%2FChicago&url=https%3A%2F%2Fredacted.callback.domain%2Fd-solo%2FttLM9YVGz%2Ftesting-dashboard%3ForgId%3D1%26theme%3Dlight%26panelId%3D2%26fullscreen%26width%3D830%26height%3D323%26tz%3DAmerica%252FChicago%26render%3D1&width=830"
t=2021-03-06T15:42:43+0000 lvl=eror msg="Remote rendering request failed" logger=rendering renderer=http error="500 Internal Server Error"
t=2021-03-06T15:42:43+0000 lvl=eror msg="Rendering failed." logger=context userId=0 orgId=1 uname= error="remote rendering request failed, status code: 500, status: 500 Internal Server Error"


Remote renderer debug logs
[0306/154213.686939:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 170: Permission denied (13)
{"url":"/render?deviceScaleFactor=1.000000&domain=redacted.domain&encoding=&height=323&renderKey=redacted&timeout=60&timezone=America%2FChicago&url=https%3A%2F%2Fredacted.domain%2Fd-solo%2FttLM9YVGz%2Ftesting-dashboard%3ForgId%3D1%26theme%3Dlight%26panelId%3D2%26fullscreen%26width%3D830%26height%3D323%26tz%3DAmerica%252FChicago%26render%3D1&width=830","stack":"Error: Timeout hit: 30000\n    at Object.<anonymous> (/usr/src/app/node_modules/puppeteer-cluster/dist/util.js:68:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/puppeteer-cluster/dist/util.js:5:58)","level":"error","message":"Request failed"}
[0306/154223.825665:ERROR:cert_issuer_source_aia.cc(104)] AiaRequest::OnFetchCompleted got error -7
[0306/154223.825729:ERROR:cert_issuer_source_aia.cc(104)] AiaRequest::OnFetchCompleted got error -301

**Comment by oholimoli** [comment] 2021-03-17 10:44
I tried it also with your configuration without success. When I try to share an image of a graph I still get the info that I must install the plugin.

The variables
```
GF_RENDERING_SERVER_URL: http://renderer:8081/render
GF_RENDERING_CALLBACK_URL: http://grafana:3000/
GF_LOG_FILTERS: rendering:debug
```
seem to have no effect :(

**Comment by Bujupah** [comment] 2021-05-27 16:12
@oholimoli 
You need to edit your Grafana config.ini file to let know that the renderer is a remote service.

**Comment by zakiharis** [comment] 2021-06-08 05:57
> @oholimoli
> You need to edit your Grafana config.ini file to let know that the renderer is a remote service.

I can confirm this is working

**Comment by AgnesToulet** [comment] 2021-06-16 15:04
Is this still an issue? I wasn't able to reproduce it using the Docker Compose example.

**Comment by oholimoli** [comment] 2021-07-15 09:15
@Bujupah would be nice if there is an easy example with a docker-compose file that comprises this modification.

**Comment by AgnesToulet** [comment] 2021-11-19 10:41
Environment variables should override the config.ini file so you shouldn't need to update it. I'm closing this as I couldn't reproduce it with latest versions. If you still have the issue, please re-poen this issue and share your exact docker-compose file and the OS Docker is running on.

**Closed by AgnesToulet** 2021-11-19 10:41 UTC
Labels: needs more info
