### ISSUE TITLE
height=-1 stop working

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana-image-renderer#380] opened 2022-11-02 12:30 UTC
**What happened**:
Using the latest version 3.6.1 setting the image `height=-1` no longer works and the image height is set to 1200.

**What you expected to happen**:
A fullpage renderer
**How to reproduce it (as minimally and precisely as possible)**:
use any grafana dashboard that is more than 1200 height and render it
**Anything else we need to know?**:
I am using repeated panels if it makes a difference.

**Environment**:
- Grafana Image Renderer version:3.6.1
- Grafana version: 9.2.3
- Installed plugin or remote renderer service: docker container
- OS Grafana Image Renderer is installed on: docker container
- User OS & Browser: docker container
- Others:

**Comment by spinillos** [comment] 2023-01-16 12:31
I understand that the issue is [here](https://github.com/grafana/grafana-image-renderer/blob/master/src/browser/browser.ts#L91-L94). This code was added to make full page screenshots and its setting the height as a proportion of the width.

`heigth=-1` previously was setting the `height` from the default config [here](https://github.com/grafana/grafana-image-renderer/blob/master/src/browser/browser.ts#L96-L98) and [here](https://github.com/grafana/grafana-image-renderer/blob/master/src/config.ts#L91).

Maybe set `height=0` does the trick.

**Comment by Clarity-89** [comment] 2023-03-31 12:42
Closing the issue for now, feel free to reopen if the issue persists.

**Closed by Clarity-89** 2023-03-31 12:42 UTC
Labels: help wanted, needs more info
